export const SITE_ORIGIN = 'https://saabbir.com';

export function canonicalForPath(pathname: string): string {
  const url = new URL(pathname || '/', SITE_ORIGIN);
  if (url.pathname !== '/' && !url.pathname.endsWith('/')) {
    url.pathname = `${url.pathname}/`;
  }
  return url.href;
}

export function articleCanonicalUrl(pathname: string, originalUrl?: string): string {
  if (originalUrl) return originalUrl;
  return canonicalForPath(pathname);
}

export function toIsoDate(value?: string | null): string | undefined {
  if (!value) return undefined;

  const dmy = value.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);
  if (dmy) {
    const [, day, month, year] = dmy;
    const parsed = new Date(`${year}-${month.padStart(2, '0')}-${day.padStart(2, '0')}T00:00:00.000Z`);
    return Number.isNaN(parsed.getTime()) ? undefined : parsed.toISOString();
  }

  const parsed = new Date(value);
  if (Number.isNaN(parsed.getTime())) return undefined;

  // Date-only strings should keep the calendar day, not shift by timezone.
  if (!/T|\d{2}:\d{2}/.test(value)) {
    const year = parsed.getFullYear();
    const month = String(parsed.getMonth() + 1).padStart(2, '0');
    const day = String(parsed.getDate()).padStart(2, '0');
    return `${year}-${month}-${day}T00:00:00.000Z`;
  }

  return parsed.toISOString();
}

export function parseContentDate(value?: string | null): Date | undefined {
  const iso = toIsoDate(value);
  if (!iso) return undefined;
  const parsed = new Date(iso);
  return Number.isNaN(parsed.getTime()) ? undefined : parsed;
}

export function contentDateValue(value?: string | null): number {
  return parseContentDate(value)?.getTime() ?? 0;
}

const DISPLAY_DATE = new Intl.DateTimeFormat('en-GB', {
  month: 'long',
  year: 'numeric',
  timeZone: 'UTC',
});

/**
 * Turns whatever a frontmatter date happens to be ("01/09/2021",
 * "12 January 2026", "2026-05-15") into one readable label: "May 2026".
 * Falls back to the raw string if it can't be parsed, so nothing disappears.
 */
export function formatDisplayDate(value?: string | null): string {
  if (!value) return '';
  const parsed = parseContentDate(value);
  if (!parsed) return value;
  return DISPLAY_DATE.format(parsed);
}

/**
 * Per-page Open Graph card. Cards are generated by
 * scripts/generate-og-images.py into public/images/og/<slug>.png; anything
 * without one falls back to the site default rather than the old headshot.
 */
export function ogImageFor(slug: string, explicit?: string | null): string {
  if (explicit) return explicit;
  return OG_SLUGS.has(slug) ? `/images/og/${slug}.png` : '/images/og/default.png';
}

// Kept as a list so a missing card degrades to the default instead of 404ing.
const OG_SLUGS = new Set([
  'work',
  'writing',
  'about',
  'wax-london-model-vs-product',
  'wax-london-homepage-performance',
  'wax-london-pdp-performance',
  'bat-uk-homepage-product-carousel',
]);
